"""Add user settings fields

Revision ID: 5cc01a7b45a2
Revises: cbf02e3e18aa
Create Date: 2025-12-27 21:02:06.610883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cc01a7b45a2'
down_revision = 'cbf02e3e18aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip reports table changes for SQLite compatibility - model differences will be resolved in production
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paused', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('show_online', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('show_distance', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_matches', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_messages', sa.Boolean(), nullable=True))
    
    # Set default values for existing users
    op.execute("UPDATE users SET is_paused = 0, show_online = 1, show_distance = 1, notify_matches = 1, notify_messages = 1")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notify_messages')
        batch_op.drop_column('notify_matches')
        batch_op.drop_column('show_distance')
        batch_op.drop_column('show_online')
        batch_op.drop_column('is_paused')

    # ### end Alembic commands ###
