"""Initial migration with traditional values

Revision ID: cbf02e3e18aa
Revises: 
Create Date: 2025-12-25 14:11:23.404985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf02e3e18aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conservatism_level', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('head_covering', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('fasting_practice', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('prayer_frequency', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('bible_reading', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('dietary_restrictions', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('family_role_view', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('wants_spouse_same_denomination', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('willing_to_relocate', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('wants_church_wedding', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('wants_church_wedding')
        batch_op.drop_column('willing_to_relocate')
        batch_op.drop_column('wants_spouse_same_denomination')
        batch_op.drop_column('family_role_view')
        batch_op.drop_column('dietary_restrictions')
        batch_op.drop_column('bible_reading')
        batch_op.drop_column('prayer_frequency')
        batch_op.drop_column('fasting_practice')
        batch_op.drop_column('head_covering')
        batch_op.drop_column('conservatism_level')

    # ### end Alembic commands ###
